name = "discord-farmbot"
main = "farmbot.js"
compatibility_date = "2023-10-30"

[vars]
# このファイルにはシークレットを保存しないでください。
# シークレットは `wrangler secret put` コマンドで設定します。

# 例:
# DISCORD_PUBLIC_KEY = "your_public_key_here"
# GOOGLE_API_KEY = "your_google_api_key_here"
